name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run build
        env:
          VITE_BASE: "/${{ github.event.repository.name }}/"
      - name: Verify build has correct base path
        run: |
          if ! grep -q "/${{ github.event.repository.name }}/" dist/index.html; then
            echo "ERROR: Built index.html does not contain correct base path /${{ github.event.repository.name }}/"
            echo "Content of dist/index.html:"
            cat dist/index.html
            exit 1
          fi
          echo "✅ Build verification passed: correct base path found in dist/index.html"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
